#!/bin/bash

# RPi Router (WiFi to Ethernet) Installer
# This script configures the Raspberry Pi to act as a router,
# sharing an internet connection from a WiFi connection (wlan0)
# to devices connected to the Ethernet port (eth0).

# Stop on any error
set -e

# --- Configuration ---
LAN_INTERFACE="eth0"
WAN_INTERFACE="wlan0" # Changed for WiFi mode
LAN_IP="192.168.88.1"
LAN_SUBNET="24"
DHCP_RANGE_START="192.168.88.2"
DHCP_RANGE_END="192.168.88.100"
DHCP_LEASE_TIME="24h"
NMCLI_CONNECTION_NAME="rpi-router-lan"

# --- Main Script ---

echo "🚀 Starting Raspberry Pi WiFi Router Setup..."
echo " सुनिश्चित करें कि आपका Pi पहले से ही वाई-फाई नेटवर्क (${WAN_INTERFACE}) से जुड़ा हुआ है。"

# 1. Install necessary packages
echo "📦 Installing dnsmasq and iptables-persistent..."
sudo apt-get update
sudo apt-get install -y dnsmasq iptables-persistent net-tools

# 2. Configure a static IP for the LAN interface
echo "⚙️ Configuring static IP ${LAN_IP}/${LAN_SUBNET} for ${LAN_INTERFACE}..."
# Check if a connection with the same name already exists and delete it
if nmcli con show "$NMCLI_CONNECTION_NAME" > /dev/null 2>&1; then
    echo "Found existing connection profile, deleting it first..."
    sudo nmcli con delete "$NMCLI_CONNECTION_NAME"
fi
sudo nmcli con add type ethernet ifname "$LAN_INTERFACE" con-name "$NMCLI_CONNECTION_NAME" autoconnect yes ip4 "${LAN_IP}/${LAN_SUBNET}"
sudo nmcli con up "$NMCLI_CONNECTION_NAME"

# 3. Configure dnsmasq as the DHCP server
echo "📝 Configuring dnsmasq for DHCP on ${LAN_INTERFACE}..."
DNSMASQ_CONF_CONTENT="
# This file was generated by the RPi Router setup script.
# DHCP server for the LAN interface
interface=${LAN_INTERFACE}
# DHCP range and lease time
dhcp-range=${DHCP_RANGE_START},${DHCP_RANGE_END},${DHCP_LEASE_TIME}
# Provide router IP as the gateway
dhcp-option=option:router,${LAN_IP}
# Use Google's DNS servers
server=8.8.8.8
server=8.8.4.4
"
echo "$DNSMASQ_CONF_CONTENT" | sudo tee /etc/dnsmasq.conf > /dev/null

# 4. Enable IP forwarding in the kernel
echo "🚦 Enabling IP forwarding..."
sudo sed -i '/^#net.ipv4.ip_forward=1/c\net.ipv4.ip_forward=1' /etc/sysctl.conf
sudo sysctl -p

# 5. Set up firewall rules with iptables
echo "🔥 Setting up firewall rules (NAT and security)..."

# Flush all existing rules to start fresh
sudo iptables -F
sudo iptables -t nat -F
sudo iptables -X

# --- FORWARD chain rules ---
# Allow established connections to return from WAN to LAN
sudo iptables -A FORWARD -i "$WAN_INTERFACE" -o "$LAN_INTERFACE" -m state --state RELATED,ESTABLISHED -j ACCEPT
# Allow all traffic from LAN to WAN
sudo iptables -A FORWARD -i "$LAN_INTERFACE" -o "$WAN_INTERFACE" -j ACCEPT

# --- NAT (Network Address Translation) ---
# Masquerade outgoing traffic from LAN to give it the WAN IP address
sudo iptables -t nat -A POSTROUTING -o "$WAN_INTERFACE" -j MASQUERADE

# --- INPUT chain security rules (hardening) ---
# Note: Applying hardening rules to wlan0 might interfere with some public WiFi networks.
# These are kept minimal.
echo "🛡️ Applying minimal security hardening rules to ${WAN_INTERFACE}..."

# Rate-limit pings to prevent ping floods
sudo iptables -A INPUT -i "$WAN_INTERFACE" -p icmp --icmp-type echo-request -m limit --limit 1/s -j ACCEPT
sudo iptables -A INPUT -i "$WAN_INTERFACE" -p icmp --icmp-type echo-request -j DROP

# 6. Save iptables rules to make them persistent
echo "💾 Saving firewall rules..."
sudo netfilter-persistent save

# 7. Restart services to apply changes
echo "🔄 Restarting dnsmasq service..."
sudo systemctl restart dnsmasq

echo ""
echo "✅ Raspberry Pi WiFi Router setup is complete!"
echo "Your Pi is now sharing the connection from ${WAN_INTERFACE} to ${LAN_INTERFACE}."
echo "Downstream devices on eth0 will receive an IP in the ${DHCP_RANGE_START} - ${DHCP_RANGE_END} range."
